export enum BANKS {
  BANCO_DE_BOGOTA = 'BANCO_DE_BOGOTA',
  BANCO_POPULAR = 'BANCO_POPULAR',
  BANCO_OCCIDENTE = 'BANCO_OCCIDENTE',
  BANCO_AV_VILLAS = 'BANCO_AV_VILLAS',
  PORVENIR = 'PORVENIR',
  FACIL_PASS = 'FACIL_PASS'
}

export const BANKS_IDS = ['0001', '0002', '0023', '0052'];

export const BANKS_OTHER: string[] = [
  BANKS.BANCO_DE_BOGOTA,
  BANKS.BANCO_OCCIDENTE,
  BANKS.BANCO_AV_VILLAS,
  BANKS.PORVENIR,
  BANKS.FACIL_PASS
];
