export enum TYPE_ACCOUNTS {
  DEPOSIT_ACCOUNT = 'DEPOSIT_ACCOUNT',
  CREDIT_CARD = 'CREDIT_CARD',
  TC = 'TC',
  CURRENT_ACCOUNT = 'CURRENT_ACCOUNT',
  CERTIFIED_DEPOSIT_TERM = 'CERTIFIED_DEPOSIT_TERM',
  FIDUCIARY = 'FIDUCIARY',
  FREE_DESTINATION = 'FREE_DESTINATION',
  DEBIT_CARD = 'DEBIT_CARD',
  PAYDAY_LOAN = 'PAYDAY_LOAN'
}

export enum TYPE_CREDIT_CARD {
  ACTIVE = 'ACTIVE'
}
